name: manage-azure-policy-f25c9a29
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Configure_Azure_Synapse_workspaces_to_use_private_DNS_zones_1e5ed725-f16c-478b-bd4b-7bfa2f7940b9/**'
#      - .github/workflows/manage-azure-policy-f25c9a29.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f25c9a29}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Configure_Azure_Synapse_workspaces_to_use_private_DNS_zones_1e5ed725-f16c-478b-bd4b-7bfa2f7940b9/**
